var username = prompt('What is your name?')
var lastname = prompt('What is last name?')
var age = prompt('What is your age?')
var hobby = prompt('Please tell me your any 1 hobby?')
alert('Your full name is ' + '= ' + username + ' ' + lastname + '\nYour age is ' + '= ' + age + '\nHere is your hobby ' + '= ' + hobby)